= Visualization framework

== Visualize component

Command line parameters of the framework. TODO
|===
|Parameter | Description | Example

| n_samples | Number of samples for each target class. If not provided, all samples will be generated. | `--n_samples 10`
| parameters| Visualization specific parameters in json format. | `--parameters={ \"colorMap\": \"OrangeBlue\", \"bottomMargin\": 25, \"scaleCoeff\": 100, \"correlationOrdering\": true}`
| parametersFile| File with visualization specific parameters in json format. | `--parametersFile config/radial_default.json`

|===

=== Breast cancer
```
./visualize.py breastCancer blobs _output/breastCancer/blobs --quantize
```
```
./visualize.py breastCancer radial _output/breastCancer/radial --n_samples 100 --quantize --parametersFile config/radial_default.json
```
```
./visualize.py breastCancer faces _output/breastCancer/faces --groups med --n_samples 100 --quantize
```

=== Nutrients
```
./visualize.py nutrients blobs _output/nutrients/blobs
```
```
./visualize.py nutrients radial _output/nutrients/radial --n_samples 10 --quantize --parametersFile config/radial_default.json
```
```
./visualize.py nutrients faces _output/nutrients/faces --groups med --n_samples 100 --quantize
```

=== Recipes
```
./visualize.py recipes blobs _output/recipes/blobs
```
```
./visualize.py recipes radial _output/recipes/radial --n_samples 100 "--parameters={ \"colorMapPath\": \"data/ingredientsMap.csv\"}"
```

=== Spotify
Takes spotify dataset (with normalization) and visualize it like blobs. Images are saved into "output" folder.

Example:
```
./visualize.py spotify blobs _output/spotify/blobs --normalize
```
```
./visualize.py spotify radial _output/spotify/radial --quantize --n_samples 100 --parametersFile config/radial_default.json
```
```
./visualize.py spotify faces _output/spotify/faces --groups med --n_samples 100 --quantize
```



== Average component

Examples:
```
./average.py _output/breastCancer/radial
./average.py _output/recipes/radial
./average.py _output/spotify/blobs
./average.py _output/spotify/radial
```

=== Selected averaging for datasets
```
./visualize.py breastCancer radial _output/breastCancer/radial --n_samples 100 --quantize --groups med --parametersFile config/radial_default.json

python visualize.py nutrients radial _output/nutrients/radial --quantize --n_samples 100 --groups med --parametersFile config/radial_default.json
```

Takes folders in "output" folder and makes average of all image in this subfolder.
